"""HTTP scanning: iterate IDs, capture response fingerprints.

The scanner's only job is to do the requests and produce `Probe` records.
It doesn't interpret them — that's analyzer.py's job.
"""
from __future__ import annotations

import hashlib
import json
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

import requests

from .config import Config, IdSpec, Scan, User

# Keep probe bodies capped so we don't blow up memory on big responses
_MAX_BODY_CAPTURE = 4096


@dataclass
class Probe:
    """A single request/response observation."""

    scan: str
    user: str  # "__unauth__" if no auth
    method: str
    url: str
    id: str
    status: int
    length: int
    content_hash: str
    location: str
    elapsed_ms: int
    body_preview: str
    error: str | None = None
    # Set to the source URL (probe that leaked this ID) when this probe
    # was generated by a harvest pass. None for first-pass probes.
    discovered_via: str | None = None

    def to_dict(self) -> dict:
        return asdict(self)


class RateLimiter:
    """Simple token-bucket-ish limiter: ensures we don't exceed N req/sec."""

    def __init__(self, per_second: float):
        self.per_second = per_second
        self._last = 0.0

    def wait(self) -> None:
        if self.per_second <= 0:
            return
        interval = 1.0 / self.per_second
        now = time.monotonic()
        delay = self._last + interval - now
        if delay > 0:
            time.sleep(delay)
        self._last = time.monotonic()


def _fingerprint(body: bytes) -> tuple[str, str]:
    """Return (sha1-truncated, utf-8 preview)."""
    digest = hashlib.sha1(body).hexdigest()[:12]
    try:
        preview = body[:_MAX_BODY_CAPTURE].decode("utf-8", errors="replace")
    except Exception:
        preview = ""
    return digest, preview


def _build_session(user: User | None, verify_tls: bool) -> requests.Session:
    s = requests.Session()
    s.verify = verify_tls
    if user is not None:
        for k, v in user.cookies.items():
            s.cookies.set(k, v)
        s.headers.update(user.headers)
    # play nice: identify ourselves
    s.headers.setdefault("User-Agent", "idor-hunter/0.1 (+authorized-testing-only)")
    return s


def _do_request(
    session: requests.Session,
    method: str,
    url: str,
    timeout: float,
    body: dict | None,
    retries: int,
) -> tuple[requests.Response | None, Exception | None]:
    last_err: Exception | None = None
    for attempt in range(retries + 1):
        try:
            kwargs = {"timeout": timeout, "allow_redirects": False}
            if body is not None and method in {"POST", "PUT", "PATCH"}:
                kwargs["json"] = body
            resp = session.request(method, url, **kwargs)
            return resp, None
        except requests.RequestException as e:
            last_err = e
            if attempt < retries:
                time.sleep(0.3 * (attempt + 1))
    return None, last_err


def _probes_for_scan(
    scan: Scan,
    config: Config,
    progress_cb=None,
    skip: set[tuple[str, str, str, str]] | None = None,
) -> Iterable[Probe]:
    limiter = RateLimiter(config.options.rate_limit)
    skip = skip or set()

    # Build the list of (user_or_None, label) that we want to probe as.
    # Dedup by label so baseline_user accidentally listed in test_users
    # doesn't create duplicate probes (analyzer's by_user dict would
    # silently drop them anyway; this makes the intent explicit).
    identities: list[tuple[User | None, str]] = []
    seen_labels: set[str] = set()

    def _add(user_obj: User | None, label: str) -> None:
        if label in seen_labels:
            return
        seen_labels.add(label)
        identities.append((user_obj, label))

    if scan.include_unauth:
        _add(None, "__unauth__")
    if scan.baseline_user:
        _add(config.user(scan.baseline_user), scan.baseline_user)
    for tu in scan.test_users:
        if tu == scan.baseline_user:
            print(
                f"  warning: scan {scan.name!r} lists baseline_user {tu!r} in "
                f"test_users; ignoring the duplicate",
                file=sys.stderr,
            )
            continue
        _add(config.user(tu), tu)

    sessions = {label: _build_session(u, config.options.verify_tls) for u, label in identities}

    ids = list(scan.ids.iter_ids())
    # Total only counts probes we'll actually issue (post-skip), so the
    # progress bar reflects remaining work, not work that was already done
    # on a prior run.
    total = sum(
        1
        for id_value in ids
        for _, label in identities
        for method in scan.methods
        if (scan.name, label, method, id_value) not in skip
    )
    done = 0

    try:
        for id_value in ids:
            url = config.base_url + scan.endpoint.replace("{id}", id_value)
            for user_obj, label in identities:
                session = sessions[label]
                for method in scan.methods:
                    if (scan.name, label, method, id_value) in skip:
                        continue
                    limiter.wait()
                    t0 = time.monotonic()
                    resp, err = _do_request(
                        session,
                        method,
                        url,
                        timeout=config.options.timeout,
                        body=scan.body,
                        retries=config.options.max_retries,
                    )
                    elapsed_ms = int((time.monotonic() - t0) * 1000)

                    if err is not None or resp is None:
                        yield Probe(
                            scan=scan.name,
                            user=label,
                            method=method,
                            url=url,
                            id=id_value,
                            status=0,
                            length=0,
                            content_hash="",
                            location="",
                            elapsed_ms=elapsed_ms,
                            body_preview="",
                            error=str(err) if err else "no response",
                        )
                    else:
                        digest, preview = _fingerprint(resp.content)
                        yield Probe(
                            scan=scan.name,
                            user=label,
                            method=method,
                            url=url,
                            id=id_value,
                            status=resp.status_code,
                            length=len(resp.content),
                            content_hash=digest,
                            location=resp.headers.get("Location", ""),
                            elapsed_ms=elapsed_ms,
                            body_preview=preview,
                        )

                    done += 1
                    if progress_cb:
                        progress_cb(done, total)
    finally:
        for s in sessions.values():
            s.close()


def _load_resume(resume_path: Path) -> tuple[list[Probe], set[tuple[str, str, str, str]]]:
    """Replay a JSONL resume log into (probes, done-coord-set).

    Malformed lines are skipped — a truncated last record from SIGKILL
    shouldn't poison the whole resume. Unknown fields are tolerated so
    older logs stay readable after Probe gains new attributes.
    """
    if not resume_path.exists():
        return [], set()
    known = {f.name for f in Probe.__dataclass_fields__.values()}
    probes: list[Probe] = []
    done: set[tuple[str, str, str, str]] = set()
    with resume_path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                data = json.loads(line)
            except json.JSONDecodeError:
                continue
            filtered = {k: v for k, v in data.items() if k in known}
            try:
                probe = Probe(**filtered)
            except TypeError:
                continue
            probes.append(probe)
            done.add((probe.scan, probe.user, probe.method, probe.id))
    return probes, done


def run_scans(
    config: Config,
    progress_cb=None,
    resume_path: Path | None = None,
) -> list[Probe]:
    """Run all scans and return every probe collected.

    If resume_path is given, probes already in the log are replayed into
    the return list and skipped on the wire — re-running a killed scan
    picks up where it left off instead of starting over.
    """
    all_probes: list[Probe] = []
    skip: set[tuple[str, str, str, str]] = set()

    if resume_path is not None:
        resume_path.parent.mkdir(parents=True, exist_ok=True)
        prior, skip = _load_resume(resume_path)
        all_probes.extend(prior)

    resume_fh = None
    if resume_path is not None:
        resume_fh = resume_path.open("a", encoding="utf-8")

    try:
        for scan in config.scans:
            for probe in _probes_for_scan(
                scan, config, progress_cb=progress_cb, skip=skip
            ):
                all_probes.append(probe)
                if resume_fh is not None:
                    resume_fh.write(json.dumps(probe.to_dict()) + "\n")
                    resume_fh.flush()
    finally:
        if resume_fh is not None:
            resume_fh.close()

    return all_probes


def run_scans_with_harvest(
    config: Config,
    progress_cb=None,
    resume_path: Path | None = None,
) -> list[Probe]:
    """Run scans, harvest UUIDs from responses, then replay them.

    Only scans with `ids.kind == "list"` get a second pass — the harvested
    values are UUIDs, not numeric, so replaying them through a numeric
    scan makes no sense.
    """
    # Import here to avoid circular (harvester imports Probe from us).
    from .harvester import harvest_uuids

    first_pass = run_scans(config, progress_cb=progress_cb, resume_path=resume_path)

    cap = config.options.harvest_max_ids
    if cap <= 0:
        return first_pass

    resume_fh = None
    if resume_path is not None:
        resume_fh = resume_path.open("a", encoding="utf-8")

    extra_probes: list[Probe] = []
    try:
        for scan in config.scans:
            if scan.ids.kind != "list":
                continue
            originals = set(scan.ids.iter_ids())
            scan_probes = [p for p in first_pass if p.scan == scan.name]
            harvested = harvest_uuids(scan_probes, originals, cap)
            if not harvested:
                continue
            source_by_uuid = {u: src for u, src in harvested}
            shadow = _replace_ids(scan, tuple(u for u, _ in harvested))
            # If resume was used, harvested probes already in first_pass
            # must not be re-issued.
            harvest_skip = {
                (p.scan, p.user, p.method, p.id)
                for p in first_pass
                if p.scan == scan.name and p.id in source_by_uuid
            }
            for probe in _probes_for_scan(
                shadow, config, progress_cb=progress_cb, skip=harvest_skip
            ):
                probe.discovered_via = source_by_uuid.get(probe.id)
                extra_probes.append(probe)
                if resume_fh is not None:
                    resume_fh.write(json.dumps(probe.to_dict()) + "\n")
                    resume_fh.flush()
    finally:
        if resume_fh is not None:
            resume_fh.close()

    return first_pass + extra_probes


def _replace_ids(scan: Scan, values: tuple[str, ...]) -> Scan:
    """Return a shadow Scan identical to `scan` but with a list IdSpec."""
    return Scan(
        name=scan.name,
        endpoint=scan.endpoint,
        methods=scan.methods,
        ids=IdSpec(kind="list", values=values),
        baseline_user=scan.baseline_user,
        test_users=scan.test_users,
        body=scan.body,
        include_unauth=scan.include_unauth,
    )
